using System.Collections.Generic;

namespace SubRenamer.Helper;

public class LocalizationHelper
{
    public static string? GetNativeName(string lang)
    {
        NativeNameMap.TryGetValue(lang.Trim().ToLower(), out var nativeName);
        return nativeName;
    }
    
    public static string? GetEnglishName(string lang)
    {
        NativeNameMap.TryGetValue(lang.Trim().ToLower(), out var nativeName);
        return nativeName;
    }


    private static readonly Dictionary<string, string> NativeNameMap = new ()
    {
        {"chi", "简体中文"},
        {"chs", "简体中文"},
        {"chn", "简体中文"},
        {"ch", "简体中文"},
        {"cn", "简体中文"},
        {"zh-cn", "简体中文"},
        {"zh-sg", "简体中文"},
        {"zh-my", "简体中文"},
    
        {"cht", "繁体中文"},
        {"zht", "繁体中文"},
        {"zh-tw", "繁体中文"},
        {"tw", "繁体中文"},
        {"zh-hk", "繁体中文"},
        {"zh-mo", "繁体中文"},
        {"hk", "繁体中文"},
        {"mo", "繁体中文"},
    
        {"zh", "中文"},
        {"zho", "中文"},
        {"chinese", "中文"},
        {"zh-chs", "简体中文"},
        {"zh-cht", "繁体中文"},
        {"zh-hans", "简体中文"},
        {"zh-hant", "繁体中文"},
        
        {"eng", "English"},
        {"english", "English"},
        {"en", "English"},
        {"us", "English"},
        {"uk", "English"},
        {"gb", "English"},
        {"us-english", "English"},
        {"uk-english", "English"},
        {"gb-english", "English"},
        
        {"jpn", "日本語"},
        {"japanese", "日本語"},
        {"ja", "日本語"},
        {"jp", "日本語"},
        
        {"kor", "한국어"},
        {"korean", "한국어"},
        {"ko", "한국어"},
        {"kr", "한국어"},
        
        {"fra", "Français"},
        {"french", "Français"},
        {"fr", "Français"},
        
        {"rus", "Русский"},
        {"russian", "Русский"},
        {"ru", "Русский"},
    };
    
    private static readonly Dictionary<string, string> EnglishNameMap = new ()
    {
        {"af", "Afrikaans"},
        {"am", "Amharic"},
        {"ar", "Arabic"},
        {"as", "Assamese"},
        {"az", "Azerbaijani"},
        {"ba", "Bashkir"},
        {"be", "Belarusian"},
        {"bg", "Bulgarian"},
        {"bn", "Bangla"},
        {"bo", "Tibetan"},
        {"br", "Breton"},
        {"bs", "Bosnian"},
        {"ca", "Catalan"},
        {"co", "Corsican"},
        {"cs", "Czech"},
        {"cy", "Welsh"},
        {"da", "Danish"},
        {"de", "German"},
        {"dv", "Dhivehi"},
        {"el", "Greek"},
        {"en", "English"},
        {"es", "Spanish"},
        {"et", "Estonian"},
        {"eu", "Basque"},
        {"fa", "Persian"},
        {"ff", "Fula"},
        {"fi", "Finnish"},
        {"fo", "Faroese"},
        {"fr", "French"},
        {"fy", "Western Frisian"},
        {"ga", "Irish"},
        {"gd", "Scottish Gaelic"},
        {"gl", "Galician"},
        {"gn", "Guarani"},
        {"gu", "Gujarati"},
        {"ha", "Hausa"},
        {"he", "Hebrew"},
        {"hi", "Hindi"},
        {"hr", "Croatian"},
        {"hu", "Hungarian"},
        {"hy", "Armenian"},
        {"id", "Indonesian"},
        {"ig", "Igbo"},
        {"ii", "Sichuan Yi"},
        {"is", "Icelandic"},
        {"it", "Italian"},
        {"iu", "Inuktitut"},
        {"ja", "Japanese"},
        {"ka", "Georgian"},
        {"kk", "Kazakh"},
        {"kl", "Kalaallisut"},
        {"km", "Khmer"},
        {"kn", "Kannada"},
        {"ko", "Korean"},
        {"ks", "Kashmiri"},
        {"ku", "Kurdish"},
        {"ky", "Kyrgyz"},
        {"lb", "Luxembourgish"},
        {"lo", "Lao"},
        {"lt", "Lithuanian"},
        {"lv", "Latvian"},
        {"mi", "Māori"},
        {"mk", "Macedonian"},
        {"ml", "Malayalam"},
        {"mn", "Mongolian"},
        {"mr", "Marathi"},
        {"ms", "Malay"},
        {"mt", "Maltese"},
        {"my", "Burmese"},
        {"nb", "Norwegian Bokmål"},
        {"ne", "Nepali"},
        {"nl", "Dutch"},
        {"nn", "Norwegian Nynorsk"},
        {"no", "Norwegian"},
        {"oc", "Occitan"},
        {"om", "Oromo"},
        {"or", "Odia"},
        {"pa", "Punjabi"},
        {"pl", "Polish"},
        {"ps", "Pashto"},
        {"pt", "Portuguese"},
        {"rm", "Romansh"},
        {"ro", "Romanian"},
        {"ru", "Russian"},
        {"rw", "Kinyarwanda"},
        {"sa", "Sanskrit"},
        {"sd", "Sindhi"},
        {"se", "Northern Sami"},
        {"si", "Sinhala"},
        {"sk", "Slovak"},
        {"sl", "Slovenian"},
        {"so", "Somali"},
        {"sq", "Albanian"},
        {"sr", "Serbian"},
        {"st", "Southern Sotho"},
        {"sv", "Swedish"},
        {"sw", "Swahili"},
        {"ta", "Tamil"},
        {"te", "Telugu"},
        {"tg", "Tajik"},
        {"th", "Thai"},
        {"ti", "Tigrinya"},
        {"tk", "Turkmen"},
        {"tn", "Tswana"},
        {"tr", "Turkish"},
        {"ts", "Tsonga"},
        {"tt", "Tatar"},
        {"ug", "Uyghur"},
        {"uk", "Ukrainian"},
        {"ur", "Urdu"},
        {"uz", "Uzbek"},
        {"ve", "Venda"},
        {"vi", "Vietnamese"},
        {"wo", "Wolof"},
        {"xh", "Xhosa"},
        {"yi", "Yiddish"},
        {"yo", "Yoruba"},
        {"zh", "Chinese"},
        {"zu", "Zulu"},
    };
}